# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My_Mapbox' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for My_Mapbox
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'ReadMoreTextView'
  pod 'MPParallaxView'



  target 'My_MapboxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'My_MapboxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
